# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/DSP-8/Desktop/lab1/lab1.cache/wt [current_project]
set_property parent.project_path C:/Users/DSP-8/Desktop/lab1/lab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/DSP-8/Desktop/lab1/lab1.srcs/sources_1/new/ha1.vhd
  C:/Users/DSP-8/Desktop/lab1/lab1.srcs/sources_1/new/fa3.vhd
}
catch { write_hwdef -file fa3.hwdef }
synth_design -top fa3 -part xc7z010clg400-1
write_checkpoint -noxdef fa3.dcp
catch { report_utilization -file fa3_utilization_synth.rpt -pb fa3_utilization_synth.pb }
